name: CI

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          # App/runtime deps
          pip install -r requirements.txt
          # Dev/CI tools
          pip install pytest pytest-cov mypy ruff black

      - name: Lint & Format
        run: |
          ruff check . --fix
          black --check .

      - name: Type check
        run: mypy api --ignore-missing-imports

      - name: Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          DISABLE_STATIC: '1'
        run: pytest -q --maxfail=1
