name: CI
on:
  push: { branches: [main] }
  pull_request: {}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install fastapi uvicorn pydantic boto3 httpx pytest pytest-cov mypy ruff black
      - name: Lint & Format
        run: |
          ruff check .
          black --check .
      - name: Type check
        run: mypy api --ignore-missing-imports
      - name: Tests
        run: pytest -q --maxfail=1
