name: CI
on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (runtime + dev)
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install ruff black mypy pytest pytest-cov httpx

      - name: Lint & Format
        run: |
          python -m ruff check . --fix
          python -m black --check .

      - name: Type check
        run: python -m mypy api --ignore-missing-imports

      - name: Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          DISABLE_STATIC: "1"
        run: python -m pytest -q --maxfail=1
