name: CI
on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (runtime + dev)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          # dev/test tools not in requirements.txt
          pip install ruff black mypy pytest pytest-cov httpx

      - name: Lint & Format
        run: |
          ruff check . --fix
          black --check .

      - name: Type check
        run: mypy api --ignore-missing-imports

      - name: Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          DISABLE_STATIC: "1"
        run: pytest -q --maxfail=1
