name: PR CI
on:
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Lint & Format
        run: |
          ruff check . --fix
          black --check .
      - name: Type check
        run: mypy api --ignore-missing-imports
      - name: Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          DISABLE_STATIC: '1'
        run: pytest -q --maxfail=1
